export const FETCHING_MESSAGES = "FETCHING_MESSAGES";
export const FETCHING_MESSAGES_SUCCESS = "FETCHING_MESSAGES_SUCCESS";
export const FETCHING_MESSAGES_FAILURE = "FETCHING_MESSAGES_FAILURE";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const ADD_MESSAGE_FAILURE = "ADD_MESSAGE_FAILURE";
